# This file is auto-generated by protoc
# Run: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. worker.proto

# Simplified version for demo - in production use actual protoc compiler
import struct
import pickle

class ExecuteTaskRequest:
    def __init__(self, task_id, stage_id, function_bytes, args, dependencies):
        self.task_id = task_id
        self.stage_id = stage_id
        self.function_bytes = function_bytes
        self.args = args
        self.dependencies = dependencies

class ExecuteTaskResponse:
    def __init__(self, task_id, success, result=None, error=None, latency_ms=0.0):
        self.task_id = task_id
        self.success = success
        self.result = result
        self.error = error
        self.latency_ms = latency_ms

class StatusRequest:
    def __init__(self, worker_id):
        self.worker_id = worker_id

class StatusResponse:
    def __init__(self, worker_id, total_tasks, completed_tasks, failed_tasks, avg_latency_ms):
        self.worker_id = worker_id
        self.total_tasks = total_tasks
        self.completed_tasks = completed_tasks
        self.failed_tasks = failed_tasks
        self.avg_latency_ms = avg_latency_ms

class ShutdownRequest:
    pass

class ShutdownResponse:
    def __init__(self, success):
        self.success = success
