apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-api
  labels:
    app: ml-pipeline-api
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: ml-pipeline-api
